/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileInfoRouteImport } from './routes/profile-info'
import { Route as ProfileAccountRouteImport } from './routes/profile-account'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const ProfileInfoRoute = ProfileInfoRouteImport.update({
  id: '/profile-info',
  path: '/profile-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountRoute = ProfileAccountRouteImport.update({
  id: '/profile-account',
  path: '/profile-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/profile-account': typeof ProfileAccountRoute
  '/profile-info': typeof ProfileInfoRoute
  '/activity/$id': typeof ActivityIdRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/profile-account': typeof ProfileAccountRoute
  '/profile-info': typeof ProfileInfoRoute
  '/activity/$id': typeof ActivityIdRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/activity': typeof ActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/profile-account': typeof ProfileAccountRoute
  '/profile-info': typeof ProfileInfoRoute
  '/activity/$id': typeof ActivityIdRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/profile-account'
    | '/profile-info'
    | '/activity/$id'
    | '/campaign/$id'
    | '/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/profile-account'
    | '/profile-info'
    | '/activity/$id'
    | '/campaign/$id'
    | '/activity'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/profile-account'
    | '/profile-info'
    | '/activity/$id'
    | '/campaign/$id'
    | '/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProfileRoute: typeof ProfileRoute
  ProfileAccountRoute: typeof ProfileAccountRoute
  ProfileInfoRoute: typeof ProfileInfoRoute
  ActivityIdRoute: typeof ActivityIdRoute
  CampaignIdRoute: typeof CampaignIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile-info': {
      id: '/profile-info'
      path: '/profile-info'
      fullPath: '/profile-info'
      preLoaderRoute: typeof ProfileInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-account': {
      id: '/profile-account'
      path: '/profile-account'
      fullPath: '/profile-account'
      preLoaderRoute: typeof ProfileAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProfileRoute: ProfileRoute,
  ProfileAccountRoute: ProfileAccountRoute,
  ProfileInfoRoute: ProfileInfoRoute,
  ActivityIdRoute: ActivityIdRoute,
  CampaignIdRoute: CampaignIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
